JobPortal2/Models/JobProvider.cs
using System.ComponentModel.DataAnnotations;

namespace JobPortal2.Models
{
    public class JobProvider
    {
        [Key]
        [DataType(DataType.EmailAddress)]
        public string EmailId  { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string? Password { get; set; }
        [Required]
        public string? FirstName { get; set; }
        [Required]
        public string? LastName { get; set; }
        public string? CompanyName { get; set; }
        public string? CompanyWebsite { get; set; }
    }
}

JobPortal2/Controllers/JobProviderController.cs
using JobPortal2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging.Signing;

namespace JobPortal2.Controllers
{
    public class JobProviderController : Controller
    {
        ProjectContext _context;
        IWebHostEnvironment _environment;
      public  JobProviderController(ProjectContext context,IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public  IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult>Register(JobProvider provider)
        {
            var jobprovider = await _context.Providers.Where(x => x.EmailId == provider.EmailId).FirstOrDefaultAsync();
            if(jobprovider!=null)
            {
                ViewBag.Message = "User already Exists";
                return View();
            }
            else
            {
                await _context.Providers.AddAsync(provider);
                await _context.SaveChangesAsync();
                return RedirectToAction("login");
            }

        }
        public IActionResult login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult>login(JobProvider provider)
        {
            var jobprovider=await _context.Providers.Where(x=>x.EmailId==provider.EmailId && x.Password==provider.Password).FirstOrDefaultAsync();
            if(jobprovider!=null)
            {
                HttpContext.Session.SetString("email", provider.EmailId);
                return RedirectToAction("Index", "Job");
            }
            else
            {
                ViewBag.Message = "Wrong Credential";
                return View();
            }
        }
        public async Task<IActionResult>jobseekerlist()
        {
            var email=HttpContext.Session.GetString("email");
            if(email==null)
            {
                return RedirectToAction("login");
            }
            var data=await _context.Seekers.ToListAsync();
            return View(data);
        }
        public async Task<IActionResult> Download(string id)
        {

            var jobseeker = await _context.Seekers.Where(x => x.JobSeekerEmail == id).FirstOrDefaultAsync();

            if (jobseeker == null)
            {
                return NotFound();
            }
            string cv = jobseeker.CV;

            var dowwnloadpath = Path.Combine(_environment.WebRootPath, "UploadFile");
            var filePath = Path.Combine(dowwnloadpath, cv);


            if (!System.IO.File.Exists(filePath))
            {
                return NotFound();
            }

            var memory = new MemoryStream();
            using (var stream = new FileStream(filePath, FileMode.Open))
            {
                stream.CopyTo(memory);
            }
            memory.Position = 0;

            return File(memory, "application/pdf", Path.GetFileName(filePath));
        }
     

    }
}

JobPortal2/Views/JobProvider/Register.cshtml
@model JobPortal2.Models.JobProvider

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>

<h4>JobProvider</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmailId" class="control-label"></label>
                <input asp-for="EmailId" class="form-control" />
                <span asp-validation-for="EmailId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyWebsite" class="control-label"></label>
                <input asp-for="CompanyWebsite" class="form-control" />
                <span asp-validation-for="CompanyWebsite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JobPortal2/Views/JobProvider/jobseekerlist.cshtml
@model IEnumerable<JobPortal2.Models.JobSeeker>

@{
    ViewData["Title"] = "jobseekerlist";
}

<h1>jobseekerlist</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
           @*  <th>
                @Html.DisplayNameFor(model => model.Password)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.Qualification)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CV)
            </th>
            <th>
                @Html.DisplayNameFor(model=>model.JobSeekerEmail)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           @*  <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td> *@
            <td>
                @Html.DisplayFor(modelItem => item.Qualification)
            </td>
            <td>
               @*  @Html.DisplayFor(modelItem => item.CV) *@
                    <a asp-controller="JobProvider" asp-action="Download" asp-route-id="@item.JobSeekerEmail">Download</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem=>item.JobSeekerEmail)
            </td>
            <td>
              @*   <a asp-action="Edit" asp-route-id="@item.JobSeekerEmail">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.JobSeekerEmail">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.JobSeekerEmail">Delete</a> *@
                     

            </td>
        </tr>
}
    </tbody>
</table>

JobPortal2/Views/JobProvider/login.cshtml
@model JobPortal2.Models.JobProvider

@{
    ViewData["Title"] = "login";
}

<h1>login</h1>

<h4>JobProvider</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmailId" class="control-label"></label>
                <input asp-for="EmailId" class="form-control" />
                <span asp-validation-for="EmailId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
          @*   <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyWebsite" class="control-label"></label>
                <input asp-for="CompanyWebsite" class="form-control" />
                <span asp-validation-for="CompanyWebsite" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}